
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'poffertjes_shop'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'poffertjes_shop'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

on-run-start:
  - "create table if not exists model_builds (model_id varchar not null, built_at timestamp not null);"
  - "create table if not exists model_starts (run_id varchar not null, started_at timestamp not null);"
  - "{{ create_or_replace_table_raw_customers() }}"
  - "{{ create_or_replace_table_raw_products() }}"
  - "{{ create_or_replace_table_raw_orders() }}"
  - "{{ create_or_replace_table_raw_order_items() }}"
  - "{{ create_or_replace_table_external_events() }}"

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

vars:
  exchange_rates:
    USD: 1.0
    EUR: 0.87
    AUD: 1.41

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
models:
  +post-hook:
    - "insert into model_builds values ('{{ this }}', current_timestamp);"
  poffertjes_shop:
    # Config indicated by + and applies to all files under models/example/
    base:
      +materialized: view      
