FROM mcr.microsoft.com/vscode/devcontainers/python:3.9

ENV PGHOST=localhost
ENV PGPASSWORD=password
ENV PGUSER=poffertjes_shop
ENV PGDATABASE=poffertjes_shop
ENV PGSCHEMA=poffertjes_shop
ENV DBT_PROFILES_DIR=/workspaces/poffertjes_shop
