version: 2

sources:
  - name: raw
    schema: public
    freshness: # default freshness
      warn_after: {count: 12, period: hour}
      error_after: {count: 24, period: hour}
    loaded_at_field: created_at    
    tables:
      - name: orders
        identifier: raw_orders
      - name: products
        identifier: raw_products
      - name: customers
        identifier: raw_customers
      - name: order_items
        identifier: raw_order_items
        freshness: # default freshness
          warn_after: {count: 1, period: hour}
          error_after: {count: 2, period: hour}
        loaded_at_field: created_at        