version: 2

sources:
  - name: raw
    schema: public
    tables:
      - name: orders
        identifier: raw_orders
      - name: products
        identifier: raw_products
      - name: customers
        identifier: raw_customers
      - name: order_items
        identifier: raw_order_items