version: 2

sources:
  - name: raw
    schema: public
    freshness: # default freshness
      warn_after: {count: 12, period: hour}
      error_after: {count: 24, period: hour}
    loaded_at_field: created_at    
    tables:
      - name: orders
        identifier: raw_orders
        description: >
          One order per record.
        columns:
          - name: order_id
            description: The order_id column
            tests:
              - not_null
              - unique
          - name: customer_id
            description: The customer_id column
            tests:
              - not_null
          - name: shoppe_id
            description: The shoppe_id column
            tests:
              - not_null
          - name: created_at
            description: The created_at column
            tests:
              - not_null
          - name: updated_at
            description: The updated_at column
            tests:
              - not_null
      - name: products
        identifier: raw_products
      - name: customers
        identifier: raw_customers
      - name: order_items
        identifier: raw_order_items
        freshness: # default freshness
          warn_after: {count: 1, period: hour}
          error_after: {count: 2, period: hour}
        loaded_at_field: created_at        